### ISSUE TITLE
Poptrox Navigations Icons are missing

### ISSUE THREAD

**Issue by SiamKreative** [SiamKreative/siamkreative.com#7]
As I removed FontAwesome, the following icons are missing:

```css
.poptrox-popup .closer:before {
    content: '\f00d';
}
.poptrox-popup .nav-previous:before {
    content: '\f104';
}
.poptrox-popup .nav-next:before {
    content: '\f105';
}
```

I need to use custom icons ([Fontello.com](http://fontello.com/) / [Fonticons.com](https://fonticons.com/)) or restore FontAwesome.
